// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItemRow: typeof import('naive-ui')['NFormItemRow']
  const NInput: typeof import('naive-ui')['NInput']
  const NTabPane: typeof import('naive-ui')['NTabPane']
  const NTabs: typeof import('naive-ui')['NTabs']
}
export {}
